import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Web3ModalProvider from "@/context/WagmiProvider";
import { cookieToInitialState } from "wagmi";
import { config } from "@/config/wagmi";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));

  return (
    <html lang="en">
      <Web3ModalProvider initialState={initialState}>
        <body className={inter.className}>{children}</body>
        <script src="https://telegram.org/js/telegram-web-app.js" async />
      </Web3ModalProvider>
    </html>
  );
}
